name: "hadolint"

on:
  pull_request:
    push:
      branches:
        - main
  workflow_dispatch:

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Hadolint Analysis
        run: docker run --rm -i hadolint/hadolint hadolint /super_calculator/Dockerfile
