name: "hadolint"

on:
  pull_request:
  push:
      branches:
        - main
  workflow_dispatch:

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Hadolint
        run: docker pull ghcr.io/hadolint/hadolint

      - name: Run Hadolint Analysis
        run: docker run --rm -i -v "${PWD}/super_calculator:/code" ghcr.io/hadolint/hadolint hadolint /code/Dockerfile
