name: lint_workflow

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
# job pour exécuter le semgrep
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Executer semgrep sur les fichiers Go
      
      # analyse semgrep avec les fichiers go
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/go"
          path: "./super_calculator/Dockerfile"
  # job pour executer hadolint        
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: executer Hadolint Analysis          
        run: |
          docker run --rm -i hadolint/hadolint < ./super_calculator/Dockerfile 
    # permet de continuer le code meme si erreur
        continue-on-error: true  
# job pour executer super lint
  super-linter:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Executer Super-Linter Analysis
        uses: github/super-linter@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          commit-sha: ${{ github.sha }}
          file-path: '.'
