name: lint_workflow

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Semgrep on Go files
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/go"
          path: "./super_calculator/Dockerfile"
          
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Hadolint Analysis
        run: |
          docker run --rm -i \
            -v ${{ github.workspace }}/super_calculator:/kamgaange \
            hadolint/hadolint \
            --config /kamgange/.hadolint.yaml \
            < /kamgaange/super_calculator/Dockerfile


  super-linter:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Super-Linter Analysis
        uses: github/super-linter@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          commit-sha: ${{ github.sha }}
          file-path: '.'
