name: test_workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
      # executer le job a chaque version de go spécifiée
        go-version: [1.17, 1.18, 1.19]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configurer Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: executer tests
      # definit le repertoire de travail pour l'execution des tests
        working-directory: ./super_calculator
        run: go test
